name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup node ${{ runner.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache ~/.npm directory
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-${{ matrix.node }}-ci-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run test
      - run: npm run lint
